# Generated by Django 5.2.7 on 2025-10-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name_plural": "Schools"},
        ),
        migrations.AlterModelOptions(
            name="schoolclass",
            options={"verbose_name_plural": "Classes"},
        ),
        migrations.AlterModelOptions(
            name="score",
            options={"verbose_name_plural": "Scores"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name_plural": "Subjects"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("student", "subject", "term", "session")},
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_rows", models.IntegerField()),
                ("success_count", models.IntegerField()),
                ("failed_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
